###
# THIS FILE IS AUTOMATICALLY GENERATED
# Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: f995bb74
# Executable: /home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa
######

###
# Build ID: f995bb74
# Source: /home/robrunne/Workspace/Simulators/ChampSim/src
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj
###

f995bb74_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj
f995bb74_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/src/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/src/*.cc))
$(f995bb74_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/src
$(f995bb74_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj/%.o: /home/robrunne/Workspace/Simulators/ChampSim/src/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/obj/*.d)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_objs_0) | /home/robrunne/Workspace/Simulators/ChampSim/bin
$(f995bb74_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
build_dirs += $(f995bb74_dirs_0) /home/robrunne/Workspace/Simulators/ChampSim/bin
build_objs += $(f995bb74_objs_0)
executable_name += /home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa

###
# Build ID: f995bb74_btbDxbtbx
# Source: /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx
###

f995bb74_btbDxbtbx_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx
f995bb74_btbDxbtbx_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/*.cc))
$(f995bb74_btbDxbtbx_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx
$(f995bb74_btbDxbtbx_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx/%.o: /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/btbDxbtbx/*.d)

$(f995bb74_btbDxbtbx_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_btbDxbtbx_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_btbDxbtbx_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_btbDxbtbx_objs_0): CPPFLAGS += -include btbDxbtbx.inc
module_dirs += $(f995bb74_btbDxbtbx_dirs_0)
module_objs += $(f995bb74_btbDxbtbx_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_btbDxbtbx_objs_0)
###
# Build ID: f995bb74_branchDtage_scl
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl
###

f995bb74_branchDtage_scl_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl
f995bb74_branchDtage_scl_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/*.cc))
$(f995bb74_branchDtage_scl_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl
$(f995bb74_branchDtage_scl_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/branchDtage_scl/*.d)

$(f995bb74_branchDtage_scl_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_branchDtage_scl_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_branchDtage_scl_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_branchDtage_scl_objs_0): CPPFLAGS += -include branchDtage_scl.inc
module_dirs += $(f995bb74_branchDtage_scl_dirs_0)
module_objs += $(f995bb74_branchDtage_scl_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_branchDtage_scl_objs_0)
###
# Build ID: f995bb74_prefetcherDfdip
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip
###

f995bb74_prefetcherDfdip_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip
f995bb74_prefetcherDfdip_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/*.cc))
$(f995bb74_prefetcherDfdip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip
$(f995bb74_prefetcherDfdip_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDfdip/*.d)

$(f995bb74_prefetcherDfdip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_prefetcherDfdip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_prefetcherDfdip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_prefetcherDfdip_objs_0): CPPFLAGS += -include prefetcherDfdip.inc
module_dirs += $(f995bb74_prefetcherDfdip_dirs_0)
module_objs += $(f995bb74_prefetcherDfdip_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_prefetcherDfdip_objs_0)
###
# Build ID: f995bb74_prefetcherDnext_line
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line
###

f995bb74_prefetcherDnext_line_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line
f995bb74_prefetcherDnext_line_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/*.cc))
$(f995bb74_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line
$(f995bb74_prefetcherDnext_line_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDnext_line/*.d)

$(f995bb74_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_prefetcherDnext_line_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
module_dirs += $(f995bb74_prefetcherDnext_line_dirs_0)
module_objs += $(f995bb74_prefetcherDnext_line_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_prefetcherDnext_line_objs_0)
###
# Build ID: f995bb74_prefetcherDno
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno
###

f995bb74_prefetcherDno_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno
f995bb74_prefetcherDno_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/*.cc))
$(f995bb74_prefetcherDno_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no
$(f995bb74_prefetcherDno_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/prefetcherDno/*.d)

$(f995bb74_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_prefetcherDno_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(f995bb74_prefetcherDno_dirs_0)
module_objs += $(f995bb74_prefetcherDno_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_prefetcherDno_objs_0)
###
# Build ID: f995bb74_replacementDlru
# Source: /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru
###

f995bb74_replacementDlru_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru
f995bb74_replacementDlru_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/*.cc))
$(f995bb74_replacementDlru_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/replacement/lru
$(f995bb74_replacementDlru_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru/%.o: /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/replacementDlru/*.d)

$(f995bb74_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(f995bb74_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(f995bb74_replacementDlru_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/f995bb74/inc
$(f995bb74_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(f995bb74_replacementDlru_dirs_0)
module_objs += $(f995bb74_replacementDlru_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/bin/11b_fa: $(f995bb74_replacementDlru_objs_0)
$(f995bb74_objs_0) $(f995bb74_btbDxbtbx_objs_0) $(f995bb74_branchDtage_scl_objs_0) $(f995bb74_prefetcherDfdip_objs_0) $(f995bb74_prefetcherDnext_line_objs_0) $(f995bb74_prefetcherDno_objs_0) $(f995bb74_replacementDlru_objs_0): CXXFLAGS += -Wall -Wno-reorder -g -O3 -I /home/robrunne/Workspace/Simulators/xed/kits/xed-install-base-2022-11-08-lin-x86-64/include
$(f995bb74_objs_0) $(f995bb74_btbDxbtbx_objs_0) $(f995bb74_branchDtage_scl_objs_0) $(f995bb74_prefetcherDfdip_objs_0) $(f995bb74_prefetcherDnext_line_objs_0) $(f995bb74_prefetcherDno_objs_0) $(f995bb74_replacementDlru_objs_0): LDLIBS += -lxed -lz -lboost_system -fsanitize=bounds -fsanitize=address -lboost_filesystem
$(f995bb74_objs_0) $(f995bb74_btbDxbtbx_objs_0) $(f995bb74_branchDtage_scl_objs_0) $(f995bb74_prefetcherDfdip_objs_0) $(f995bb74_prefetcherDnext_line_objs_0) $(f995bb74_prefetcherDno_objs_0) $(f995bb74_replacementDlru_objs_0): LDFLAGS += -L/home/robrunne/Workspace/Simulators/xed/kits/xed-install-base-2022-11-08-lin-x86-64/lib -fsanitize=bounds -fsanitize=address

######
# Build ID: cbf21a8f
# Executable: /home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main
######

###
# Build ID: cbf21a8f
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/src
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
###

cbf21a8f_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
cbf21a8f_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/src/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/src/*.cc))
$(cbf21a8f_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/src
$(cbf21a8f_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/src/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/*.d)

###
# Build ID: cbf21a8f
# Source: /home/robrunne/Workspace/Simulators/ChampSim/src
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
###

cbf21a8f_dirs_1 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
cbf21a8f_objs_1 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/src/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/src/*.cc))
$(cbf21a8f_objs_1): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/src
$(cbf21a8f_objs_1): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/%.o: /home/robrunne/Workspace/Simulators/ChampSim/src/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/obj/*.d)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_objs_0) $(cbf21a8f_objs_1) | /home/robrunne/Workspace/Simulators/ChampSim/test/bin
$(cbf21a8f_objs_0) $(cbf21a8f_objs_1): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
build_dirs += $(cbf21a8f_dirs_0) $(cbf21a8f_dirs_1) /home/robrunne/Workspace/Simulators/ChampSim/test/bin
build_objs += $(cbf21a8f_objs_0) $(cbf21a8f_objs_1)
executable_name += /home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main

###
# Build ID: cbf21a8f_btbDbasic_btb
# Source: /home/robrunne/Workspace/Simulators/ChampSim/btb/basic_btb
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb
###

cbf21a8f_btbDbasic_btb_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb
cbf21a8f_btbDbasic_btb_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/btb/basic_btb/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/btb/basic_btb/*.cc))
$(cbf21a8f_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/btb/basic_btb
$(cbf21a8f_btbDbasic_btb_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb/%.o: /home/robrunne/Workspace/Simulators/ChampSim/btb/basic_btb/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDbasic_btb/*.d)

$(cbf21a8f_btbDbasic_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_btbDbasic_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_btbDbasic_btb_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_btbDbasic_btb_objs_0): CPPFLAGS += -include btbDbasic_btb.inc
module_dirs += $(cbf21a8f_btbDbasic_btb_dirs_0)
module_objs += $(cbf21a8f_btbDbasic_btb_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_btbDbasic_btb_objs_0)
###
# Build ID: cbf21a8f_btbDtagging_btb
# Source: /home/robrunne/Workspace/Simulators/ChampSim/btb/tagging_btb
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb
###

cbf21a8f_btbDtagging_btb_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb
cbf21a8f_btbDtagging_btb_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/btb/tagging_btb/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/btb/tagging_btb/*.cc))
$(cbf21a8f_btbDtagging_btb_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/btb/tagging_btb
$(cbf21a8f_btbDtagging_btb_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb/%.o: /home/robrunne/Workspace/Simulators/ChampSim/btb/tagging_btb/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDtagging_btb/*.d)

$(cbf21a8f_btbDtagging_btb_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_btbDtagging_btb_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_btbDtagging_btb_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_btbDtagging_btb_objs_0): CPPFLAGS += -include btbDtagging_btb.inc
module_dirs += $(cbf21a8f_btbDtagging_btb_dirs_0)
module_objs += $(cbf21a8f_btbDtagging_btb_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_btbDtagging_btb_objs_0)
###
# Build ID: cbf21a8f_btbDxbtbx
# Source: /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx
###

cbf21a8f_btbDxbtbx_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx
cbf21a8f_btbDxbtbx_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/*.cc))
$(cbf21a8f_btbDxbtbx_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx
$(cbf21a8f_btbDxbtbx_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx/%.o: /home/robrunne/Workspace/Simulators/ChampSim/btb/xbtbx/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/btbDxbtbx/*.d)

$(cbf21a8f_btbDxbtbx_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_btbDxbtbx_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_btbDxbtbx_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_btbDxbtbx_objs_0): CPPFLAGS += -include btbDxbtbx.inc
module_dirs += $(cbf21a8f_btbDxbtbx_dirs_0)
module_objs += $(cbf21a8f_btbDxbtbx_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_btbDxbtbx_objs_0)
###
# Build ID: cbf21a8f_branchDbimodal
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/bimodal
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal
###

cbf21a8f_branchDbimodal_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal
cbf21a8f_branchDbimodal_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/bimodal/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/bimodal/*.cc))
$(cbf21a8f_branchDbimodal_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/bimodal
$(cbf21a8f_branchDbimodal_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/bimodal/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDbimodal/*.d)

$(cbf21a8f_branchDbimodal_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_branchDbimodal_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_branchDbimodal_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_branchDbimodal_objs_0): CPPFLAGS += -include branchDbimodal.inc
module_dirs += $(cbf21a8f_branchDbimodal_dirs_0)
module_objs += $(cbf21a8f_branchDbimodal_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_branchDbimodal_objs_0)
###
# Build ID: cbf21a8f_branchDgshare
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/gshare
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare
###

cbf21a8f_branchDgshare_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare
cbf21a8f_branchDgshare_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/gshare/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/gshare/*.cc))
$(cbf21a8f_branchDgshare_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/gshare
$(cbf21a8f_branchDgshare_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/gshare/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDgshare/*.d)

$(cbf21a8f_branchDgshare_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_branchDgshare_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_branchDgshare_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_branchDgshare_objs_0): CPPFLAGS += -include branchDgshare.inc
module_dirs += $(cbf21a8f_branchDgshare_dirs_0)
module_objs += $(cbf21a8f_branchDgshare_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_branchDgshare_objs_0)
###
# Build ID: cbf21a8f_branchDhashed_perceptron
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/hashed_perceptron
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron
###

cbf21a8f_branchDhashed_perceptron_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron
cbf21a8f_branchDhashed_perceptron_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/hashed_perceptron/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/hashed_perceptron/*.cc))
$(cbf21a8f_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/hashed_perceptron
$(cbf21a8f_branchDhashed_perceptron_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/hashed_perceptron/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDhashed_perceptron/*.d)

$(cbf21a8f_branchDhashed_perceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_branchDhashed_perceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_branchDhashed_perceptron_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_branchDhashed_perceptron_objs_0): CPPFLAGS += -include branchDhashed_perceptron.inc
module_dirs += $(cbf21a8f_branchDhashed_perceptron_dirs_0)
module_objs += $(cbf21a8f_branchDhashed_perceptron_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_branchDhashed_perceptron_objs_0)
###
# Build ID: cbf21a8f_branchDperceptron
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/perceptron
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron
###

cbf21a8f_branchDperceptron_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron
cbf21a8f_branchDperceptron_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/perceptron/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/perceptron/*.cc))
$(cbf21a8f_branchDperceptron_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/perceptron
$(cbf21a8f_branchDperceptron_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/perceptron/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDperceptron/*.d)

$(cbf21a8f_branchDperceptron_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_branchDperceptron_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_branchDperceptron_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_branchDperceptron_objs_0): CPPFLAGS += -include branchDperceptron.inc
module_dirs += $(cbf21a8f_branchDperceptron_dirs_0)
module_objs += $(cbf21a8f_branchDperceptron_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_branchDperceptron_objs_0)
###
# Build ID: cbf21a8f_branchDtage_scl
# Source: /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl
###

cbf21a8f_branchDtage_scl_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl
cbf21a8f_branchDtage_scl_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/*.cc))
$(cbf21a8f_branchDtage_scl_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl
$(cbf21a8f_branchDtage_scl_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl/%.o: /home/robrunne/Workspace/Simulators/ChampSim/branch/tage_scl/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/branchDtage_scl/*.d)

$(cbf21a8f_branchDtage_scl_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_branchDtage_scl_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_branchDtage_scl_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_branchDtage_scl_objs_0): CPPFLAGS += -include branchDtage_scl.inc
module_dirs += $(cbf21a8f_branchDtage_scl_dirs_0)
module_objs += $(cbf21a8f_branchDtage_scl_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_branchDtage_scl_objs_0)
###
# Build ID: cbf21a8f_prefetcherDfdip
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip
###

cbf21a8f_prefetcherDfdip_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip
cbf21a8f_prefetcherDfdip_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/*.cc))
$(cbf21a8f_prefetcherDfdip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip
$(cbf21a8f_prefetcherDfdip_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/fdip/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDfdip/*.d)

$(cbf21a8f_prefetcherDfdip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDfdip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDfdip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDfdip_objs_0): CPPFLAGS += -include prefetcherDfdip.inc
module_dirs += $(cbf21a8f_prefetcherDfdip_dirs_0)
module_objs += $(cbf21a8f_prefetcherDfdip_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDfdip_objs_0)
###
# Build ID: cbf21a8f_prefetcherDip_stride
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/ip_stride
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride
###

cbf21a8f_prefetcherDip_stride_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride
cbf21a8f_prefetcherDip_stride_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/ip_stride/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/ip_stride/*.cc))
$(cbf21a8f_prefetcherDip_stride_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/ip_stride
$(cbf21a8f_prefetcherDip_stride_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/ip_stride/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDip_stride/*.d)

$(cbf21a8f_prefetcherDip_stride_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDip_stride_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDip_stride_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDip_stride_objs_0): CPPFLAGS += -include prefetcherDip_stride.inc
module_dirs += $(cbf21a8f_prefetcherDip_stride_dirs_0)
module_objs += $(cbf21a8f_prefetcherDip_stride_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDip_stride_objs_0)
###
# Build ID: cbf21a8f_prefetcherDnext_line
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line
###

cbf21a8f_prefetcherDnext_line_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line
cbf21a8f_prefetcherDnext_line_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/*.cc))
$(cbf21a8f_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line
$(cbf21a8f_prefetcherDnext_line_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line/*.d)

$(cbf21a8f_prefetcherDnext_line_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDnext_line_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDnext_line_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDnext_line_objs_0): CPPFLAGS += -include prefetcherDnext_line.inc
module_dirs += $(cbf21a8f_prefetcherDnext_line_dirs_0)
module_objs += $(cbf21a8f_prefetcherDnext_line_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDnext_line_objs_0)
###
# Build ID: cbf21a8f_prefetcherDnext_line_instr
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line_instr
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr
###

cbf21a8f_prefetcherDnext_line_instr_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr
cbf21a8f_prefetcherDnext_line_instr_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line_instr/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line_instr/*.cc))
$(cbf21a8f_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line_instr
$(cbf21a8f_prefetcherDnext_line_instr_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/next_line_instr/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDnext_line_instr/*.d)

$(cbf21a8f_prefetcherDnext_line_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDnext_line_instr_objs_0): CPPFLAGS += -include prefetcherDnext_line_instr.inc
module_dirs += $(cbf21a8f_prefetcherDnext_line_instr_dirs_0)
module_objs += $(cbf21a8f_prefetcherDnext_line_instr_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDnext_line_instr_objs_0)
###
# Build ID: cbf21a8f_prefetcherDno
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno
###

cbf21a8f_prefetcherDno_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno
cbf21a8f_prefetcherDno_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/*.cc))
$(cbf21a8f_prefetcherDno_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no
$(cbf21a8f_prefetcherDno_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno/*.d)

$(cbf21a8f_prefetcherDno_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDno_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDno_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDno_objs_0): CPPFLAGS += -include prefetcherDno.inc
module_dirs += $(cbf21a8f_prefetcherDno_dirs_0)
module_objs += $(cbf21a8f_prefetcherDno_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDno_objs_0)
###
# Build ID: cbf21a8f_prefetcherDno_instr
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no_instr
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr
###

cbf21a8f_prefetcherDno_instr_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr
cbf21a8f_prefetcherDno_instr_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no_instr/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no_instr/*.cc))
$(cbf21a8f_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no_instr
$(cbf21a8f_prefetcherDno_instr_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/no_instr/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDno_instr/*.d)

$(cbf21a8f_prefetcherDno_instr_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDno_instr_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDno_instr_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDno_instr_objs_0): CPPFLAGS += -include prefetcherDno_instr.inc
module_dirs += $(cbf21a8f_prefetcherDno_instr_dirs_0)
module_objs += $(cbf21a8f_prefetcherDno_instr_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDno_instr_objs_0)
###
# Build ID: cbf21a8f_prefetcherDspp_dev
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/spp_dev
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev
###

cbf21a8f_prefetcherDspp_dev_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev
cbf21a8f_prefetcherDspp_dev_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/spp_dev/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/spp_dev/*.cc))
$(cbf21a8f_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/spp_dev
$(cbf21a8f_prefetcherDspp_dev_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/spp_dev/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDspp_dev/*.d)

$(cbf21a8f_prefetcherDspp_dev_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDspp_dev_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDspp_dev_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDspp_dev_objs_0): CPPFLAGS += -include prefetcherDspp_dev.inc
module_dirs += $(cbf21a8f_prefetcherDspp_dev_dirs_0)
module_objs += $(cbf21a8f_prefetcherDspp_dev_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDspp_dev_objs_0)
###
# Build ID: cbf21a8f_prefetcherDva_ampm_lite
# Source: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/va_ampm_lite
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite
###

cbf21a8f_prefetcherDva_ampm_lite_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite
cbf21a8f_prefetcherDva_ampm_lite_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/va_ampm_lite/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/va_ampm_lite/*.cc))
$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/prefetcher/va_ampm_lite
$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite/%.o: /home/robrunne/Workspace/Simulators/ChampSim/prefetcher/va_ampm_lite/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/prefetcherDva_ampm_lite/*.d)

$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_prefetcherDva_ampm_lite_objs_0): CPPFLAGS += -include prefetcherDva_ampm_lite.inc
module_dirs += $(cbf21a8f_prefetcherDva_ampm_lite_dirs_0)
module_objs += $(cbf21a8f_prefetcherDva_ampm_lite_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_prefetcherDva_ampm_lite_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/address_collector
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector
###

cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector
cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/address_collector/*.cc))
$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/address_collector
$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/address_collector/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDaddress_collector/*.d)

$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDaddress_collector.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDprefetcherDaddress_collector_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_collector
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector
###

cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector
cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_collector/*.cc))
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_collector
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_collector/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_collector/*.d)

$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_collector.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_collector_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter
###

cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter
cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/*.cc))
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_emitter
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/metadata_emitter/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDmetadata_emitter/*.d)

$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDmetadata_emitter.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDprefetcherDmetadata_emitter_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector
###

cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector
cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/*.cc))
$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector
$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/prefetcher/prefetch_hit_collector/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDprefetcherDprefetch_hit_collector/*.d)

$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0): CPPFLAGS += -include testDcppDmodulesDprefetcherDprefetch_hit_collector.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDprefetcherDprefetch_hit_collector_objs_0)
###
# Build ID: cbf21a8f_replacementDdrrip
# Source: /home/robrunne/Workspace/Simulators/ChampSim/replacement/drrip
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip
###

cbf21a8f_replacementDdrrip_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip
cbf21a8f_replacementDdrrip_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/replacement/drrip/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/replacement/drrip/*.cc))
$(cbf21a8f_replacementDdrrip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/replacement/drrip
$(cbf21a8f_replacementDdrrip_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip/%.o: /home/robrunne/Workspace/Simulators/ChampSim/replacement/drrip/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDdrrip/*.d)

$(cbf21a8f_replacementDdrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_replacementDdrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_replacementDdrrip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_replacementDdrrip_objs_0): CPPFLAGS += -include replacementDdrrip.inc
module_dirs += $(cbf21a8f_replacementDdrrip_dirs_0)
module_objs += $(cbf21a8f_replacementDdrrip_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_replacementDdrrip_objs_0)
###
# Build ID: cbf21a8f_replacementDlru
# Source: /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru
###

cbf21a8f_replacementDlru_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru
cbf21a8f_replacementDlru_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/*.cc))
$(cbf21a8f_replacementDlru_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/replacement/lru
$(cbf21a8f_replacementDlru_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru/%.o: /home/robrunne/Workspace/Simulators/ChampSim/replacement/lru/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDlru/*.d)

$(cbf21a8f_replacementDlru_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_replacementDlru_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_replacementDlru_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_replacementDlru_objs_0): CPPFLAGS += -include replacementDlru.inc
module_dirs += $(cbf21a8f_replacementDlru_dirs_0)
module_objs += $(cbf21a8f_replacementDlru_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_replacementDlru_objs_0)
###
# Build ID: cbf21a8f_replacementDship
# Source: /home/robrunne/Workspace/Simulators/ChampSim/replacement/ship
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship
###

cbf21a8f_replacementDship_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship
cbf21a8f_replacementDship_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/replacement/ship/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/replacement/ship/*.cc))
$(cbf21a8f_replacementDship_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/replacement/ship
$(cbf21a8f_replacementDship_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship/%.o: /home/robrunne/Workspace/Simulators/ChampSim/replacement/ship/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDship/*.d)

$(cbf21a8f_replacementDship_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_replacementDship_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_replacementDship_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_replacementDship_objs_0): CPPFLAGS += -include replacementDship.inc
module_dirs += $(cbf21a8f_replacementDship_dirs_0)
module_objs += $(cbf21a8f_replacementDship_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_replacementDship_objs_0)
###
# Build ID: cbf21a8f_replacementDsrrip
# Source: /home/robrunne/Workspace/Simulators/ChampSim/replacement/srrip
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip
###

cbf21a8f_replacementDsrrip_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip
cbf21a8f_replacementDsrrip_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/replacement/srrip/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/replacement/srrip/*.cc))
$(cbf21a8f_replacementDsrrip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/replacement/srrip
$(cbf21a8f_replacementDsrrip_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip/%.o: /home/robrunne/Workspace/Simulators/ChampSim/replacement/srrip/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/replacementDsrrip/*.d)

$(cbf21a8f_replacementDsrrip_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_replacementDsrrip_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_replacementDsrrip_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_replacementDsrrip_objs_0): CPPFLAGS += -include replacementDsrrip.inc
module_dirs += $(cbf21a8f_replacementDsrrip_dirs_0)
module_objs += $(cbf21a8f_replacementDsrrip_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_replacementDsrrip_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDreplacementDlru_collect
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/lru_collect
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect
###

cbf21a8f_testDcppDmodulesDreplacementDlru_collect_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect
cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/lru_collect/*.cc))
$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/lru_collect
$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/lru_collect/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDlru_collect/*.d)

$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDlru_collect.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDreplacementDlru_collect_objs_0)
###
# Build ID: cbf21a8f_testDcppDmodulesDreplacementDmock_replacement
# Source: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/mock_replacement
# Destination: /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement
###

cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_dirs_0 = /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement
cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0 = $(patsubst /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc, /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement/%.o, $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/mock_replacement/*.cc))
$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/mock_replacement
$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement/%.o: /home/robrunne/Workspace/Simulators/ChampSim/test/cpp/modules/replacement/mock_replacement/%.cc | /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement
-include $(wildcard /home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/testDcppDmodulesDreplacementDmock_replacement/*.d)

$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): CXXFLAGS += -Wno-unused-parameter
$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -DCHAMPSIM_MODULE
$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -I/home/robrunne/Workspace/Simulators/ChampSim/.csconfig/test/cbf21a8f/inc
$(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0): CPPFLAGS += -include testDcppDmodulesDreplacementDmock_replacement.inc
module_dirs += $(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_dirs_0)
module_objs += $(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0)

/home/robrunne/Workspace/Simulators/ChampSim/test/bin/000-test-main: $(cbf21a8f_testDcppDmodulesDreplacementDmock_replacement_objs_0)
