#!/bin/bash

module load Python/3.12.3-GCCcore-13.3.0
module load GCC/13.3.0
module load GCCcore/13.3.0

bin="bin/btb_4k_baseline/btb_tag_full"
dir="single_baseline"
count=1
timelimit="3:00:00"

echo "${bin}"
# IPC-1 Benchmarks
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=20G -n1 -c8 -t$timelimit -o /cluster/work/users/romankb/latency-spec-$(basename ${bin})-%j.out   -e /cluster/work/users/romankb/latency-spec-$(basename ${bin})-%j.err     python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --traces_directory /cluster/projects/nn4650k/dataset/ipc1_new/spec   --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/ipc1_spec/sizes_$(basename ${bin})/   &>> /cluster/work/users/romankb/pyrunner_latency_fixed_ipc1_spec_$(basename ${bin}).log &
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=20G -n1 -c8 -t$timelimit -o /cluster/work/users/romankb/latency-client-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-client-$(basename ${bin})-%j.err   python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --traces_directory /cluster/projects/nn4650k/dataset/ipc1_new/client --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/ipc1_client/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_ipc1_client_$(basename ${bin}).log &
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=20G -n1 -c8 -t$timelimit -o /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.err   python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --traces_directory /cluster/projects/nn4650k/dataset/ipc1_new/server --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/ipc1_server/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_ipc1_server_$(basename ${bin}).log &
# SPECCPU / DPC-3 Benchmarks
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=20G -n1 -c8 -t$timelimit -o /cluster/work/users/romankb/latency-speccpu-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-speccpu-$(basename ${bin})-%j.err python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/speccpu --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/dpc3/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_dpc3_$(basename ${bin}).log &
# LLBP Benchmarks
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=20G -n1 -c8 -t$timelimit -o /cluster/work/users/romankb/latency-llbp-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-llbp-$(basename ${bin})-%j.err       python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/LLBP    --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/LLBP/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_llbp_$(basename ${bin}).log &
# Google Traces / No performance benchmark as no dependency information
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=8G -n1 -c20 -t$timelimit -o /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.err python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/google/delta    --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/google_delta/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_google_delta_$(basename ${bin}).log &
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=8G -n1 -c20 -t$timelimit -o /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.err python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/google/whiskey  --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/google_whiskey/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_google_whiskey_$(basename ${bin}).log &
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=8G -n1 -c20 -t$timelimit -o /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.err python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/google/charlie  --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/google_charlie/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_google_charlie_$(basename ${bin}).log &
srun --account=nn4650k -J num-collection-$(basename ${bin}) --mail-user=romankb@ntnu.no --mail-type=FAIL --mem-per-cpu=8G -n1 -c20 -t$timelimit -o /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.out -e /cluster/work/users/romankb/latency-server-$(basename ${bin})-%j.err python /cluster/projects/nn4650k/workspace/ChampSim/data_collector.py --warmup 100000000 --evaluation 100000000 --experiment_executable ${bin} --intel --traces_directory /cluster/projects/nn4650k/dataset/google/merced   --nosub --output_dir /cluster/work/users/romankb/results/${dir}_${count}/google_merced/sizes_$(basename ${bin})/ &>> /cluster/work/users/romankb/pyrunner_latency_fixed_google_merced_$(basename ${bin}).log &

for job in `jobs -p`
do
    echo $job
    wait $job
done
