#!/bin/bash

configurations_arm=("sizes_champsim_data_32k" "sizes_champsim_data_64k")

#configurations_x86=("sizes_champsim32k" "sizes_champsim64k")
pg_dir=""

if [ -z ${plotgen_dir+x} ]; then pg_dir=""; else pg_dir=$plotgen_dir; fi

echo ${pg_dir}

# Tanvir Workloads
for config in ${configurations_x86[@]}
do
    echo "${pg_dir}plotgen --debug -i ./tanvir/sizes_*champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv -i ./tanvir/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./tanvir/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    ${pg_dir}plotgen --debug -i ./tanvir/sizes_champsim*k/**/cpu0_L1I_num_cl_with_block_size.tsv ./tanvir/sizes_champsim_vcl_buffer_*/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html
    ${pg_dir}plotgen --debug -i ./tanvir/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./tanvir/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.html
    ${pg_dir}plotgen --debug -i ./tanvir/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./tanvir/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}.tsv -o ./graphs/block_sizes_buffer_bar_${application}.html
    ${pg_dir}plotgen --debug -i ./tanvir/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./tanvir/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_bar_${application}_accesses_scaled.html
done

for config in ${configurations_arm[@]}
do
    # IPC 1 spec Workload
    # echo "${pg_dir}plotgen --debug -i ./ipc1_spec/sizes_*champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv -i ./ipc1_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./ipc1_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    # ${pg_dir}plotgen --debug -i ./ipc1_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./ipc1_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html
    # ${pg_dir}plotgen --debug -i ./ipc1_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./ipc1_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filenameframes .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}.tsv -o ./graphs/block_sizes_buffer_bar_${application}.html
    # ${pg_dir}plotgen --debug -i ./ipc1_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./ipc1_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.html
    # ${pg_dir}plotgen --debug -i ./ipc1_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./ipc1_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filenameframes .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_bar_${application}_accesses_scaled.html
    # IPC 1 server Workload
    echo "${pg_dir}plotgen --debug -i ./ipc1_server/sizes_*champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv -i ./ipc1_server/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./ipc1_server/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns :--join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    ${pg_dir}plotgen --debug -i ./ipc1_server/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_ipc1_server.tsv -o ./graphs/block_sizes_accum_normalised_${config}_ipc1_server.html
    ${pg_dir}plotgen --debug -i ./ipc1_server/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_ipc1_server.tsv -o ./graphs/block_sizes_${config}_ipc1_server.html
    ${pg_dir}plotgen --debug -i ./ipc1_server/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_ipc1_server_accesses_scaled.tsv -o ./graphs/block_sizes_accum_normalised_${config}_ipc1_server_accesses_scaled.html
    ${pg_dir}plotgen --debug -i ./ipc1_server/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_ipc1_server_accesses_scaled.tsv -o ./graphs/block_sizes_${config}_ipc1_server_accesses_scaled.html

    # IPC 1 client 
    echo "~/Workspace/plotgen/plotgen --debug -i ./ipc1_client/sizes_champsim*k/**/cpu0_L1I_num_cl_with_block_size.tsv ./ipc1_client/sizes_champsim_vcl_buffer_*/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv ./ipc1_client/sizes_champsim_simple_vcl_buffer_64_lru_8w/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./([a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    ${pg_dir}plotgen --debug -i ./ipc1_client/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_ipc1_client.tsv -o ./graphs/block_sizes_accum_normalised_${config}_ipc1_client.html
    ${pg_dir}plotgen --debug -i ./ipc1_client/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_ipc1_client.tsv -o ./graphs/block_sizes_${config}_ipc1_client.html
    ${pg_dir}plotgen --debug -i ./ipc1_client/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_ipc1_client_accesses_scaled.tsv -o ./graphs/block_sizes_accum_normalised_${config}_ipc1_client_accesses_scaled.html
    ${pg_dir}plotgen --debug -i ./ipc1_client/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_ipc1_client_accesses_scaled.tsv -o ./graphs/block_sizes_${config}_ipc1_client_accesses_scaled.html

    # CRC 2 cloud Workload
    # echo "~/Workspace/plotgen/plotgen --debug -i ./crc2_cloud/sizes_champsim*k/**/cpu0_L1I_num_cl_with_block_size.tsv ./crc2_cloud/sizes_champsim_vcl_buffer_*/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv ./ipc1_client/sizes_champsim_simple_vcl_buffer_64_lru_8w/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./([a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    ${pg_dir}plotgen --debug -i ./crc2_cloud/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_crc2_cloud.tsv -o ./graphs/block_sizes_accum_normalised_${config}_crc2_cloud.html
    ${pg_dir}plotgen --debug -i ./crc2_cloud/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_crc2_cloud.tsv -o ./graphs/block_sizes_${config}_crc2_cloud.html
    ${pg_dir}plotgen --debug -i ./crc2_cloud/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_crc2_cloud.tsv -o ./graphs/block_sizes_accum_normalised_${config}_crc2_cloud.html
    ${pg_dir}plotgen --debug -i ./crc2_cloud/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_crc2_cloud.tsv -o ./graphs/block_sizes_${config}_crc2_cloud.html

    # CRC 2 spec Workload
    # echo "~/Workspace/plotgen/plotgen --debug -i ./crc2_spec/sizes_champsim*k/**/cpu0_L1I_num_cl_with_block_size.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv ./ipc1_client/sizes_champsim_simple_vcl_buffer_64_lru_8w/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./([a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    # ${pg_dir}plotgen --debug -i ./crc2_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html
    # ${pg_dir}plotgen --debug -i ./crc2_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}.tsv -o ./graphs/block_sizes_buffer_bar_${application}.html
    # ${pg_dir}plotgen --debug -i ./crc2_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}_accesses_scaled.html
    # ${pg_dir}plotgen --debug -i ./crc2_spec/sizes_champsim*k/${application}/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/${application}/cpu0_L1I_buffer_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --select-frames .*${application}.* --join index --column-names --renameregex '\./.*/(sizes_champsim[a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_bar_${application}_accesses_scaled.tsv -o ./graphs/block_sizes_buffer_bar_${application}_accesses_scaled.html
    # DPC 3 spec Workload
    # echo "~/Workspace/plotgen/plotgen --debug -i ./crc2_spec/sizes_champsim*k/**/cpu0_L1I_num_cl_with_block_size.tsv ./crc2_spec/sizes_champsim_vcl_buffer_*/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv ./ipc1_client/sizes_champsim_simple_vcl_buffer_64_lru_8w/**/cpu0_L1I_buffer_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --select-frames .*${application}.* --join index --column-names --renameregex '\./([a-zA-Z\-_0-9]+)\.*' --palette bright --plot bar --file ./raw_data/block_sizes_buffer_accum_avg_bar_${application}.tsv -o ./graphs/block_sizes_buffer_accum_avg_bar_${application}.html"
    ${pg_dir}plotgen --debug -i ./dpc3/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_dpc3.tsv -o ./graphs/block_sizes_accum_normalised_${config}_dpc3.html
    ${pg_dir}plotgen --debug -i ./dpc3/${config}/**/cpu0_L1I_num_cl_with_block_size.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_dpc3.tsv -o ./graphs/block_sizes_${config}_dpc3.html
    ${pg_dir}plotgen --debug -i ./dpc3/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --apply-func cumsum --apply-columns : --normalise-function max --normalise-icolumns : --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --add-func min --add-column min --add-func max --add-column max --palette bright --plot bar --file ./raw_data/block_sizes_accum_normalised_${config}_dpc3.tsv -o ./graphs/block_sizes_accum_normalised_${config}_dpc3.html
    ${pg_dir}plotgen --debug -i ./dpc3/${config}/**/cpu0_L1I_num_cl_with_block_size_accesses_scaled.tsv --no-columns --frame-names --filename --column-names --filename --join index --column-names --renameregex '\./.*/.*/([a-zA-Z\-_0-9\.]+)/\.*' --palette bright --plot bar --file ./raw_data/block_sizes_${config}_dpc3.tsv -o ./graphs/block_sizes_${config}_dpc3.html

done


echo "DONE"
